name: 'Setup Varbase AI'
description: 'A Drupal recipe to setup default Varbase AI installed modules, configs and permissions.'
type: 'optional'

install:
  - varbase_ai

config:
  import:
    varbase_ai: '*'
