name: 'Setup Varbase AI'
description: 'A Drupal recipe to setup default Varbase AI needed modules, import configs and grant permissions.'
type: 'optional'
install:
  - ai
  - ai_provider_openai
  - ai_image_alt_text
  - ai_assistant_api
  - ai_ckeditor
config:
  import:
    ai: '*'
    ai_image_alt_text: '*'
    ai_ckeditor: '*'
  actions:
    user.role.site_admin:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
    user.role.content_admin:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
    user.role.editor:
      grantPermissions:
        - 'generate ai alt tags'
        - 'use ai ckeditor'
